### ISSUE TITLE
encode ok, but decode failed [JIRA: RIAK-3393]

### ISSUE THREAD

**Issue by bighunter513** [basho/erlang_protobuffs#104]
our project has a proto define as follows:
message A1 {
optional uint32 a = 1;
}
message A2 {
optional uint32 b = 1;
optional string  c = 2;
}

message C {
optional A1  a1 = 1;
}
其中
record C 正确的情况下包含了一个A1， 但是一次程序误操作，将C里面的A1保存成了A2， 这两个在某些时候会互相转换。 然后在存db的时候，encode成功，但是下次启动服务器后，decode一直失败。
当然实际结构比这个复杂，查了很久，发现是存的地方写混淆了。 不过如果pb在encode的时候能做严格的检查  就会更早的发现这个问题了。

**Comment by lukebakken** [comment]
@bighunter513 - please use [`gpb`](https://github.com/tomas-abrahamsson/gpb). This project is no longer actively maintained.
