### ISSUE TITLE
protobuf3 support? [JIRA: RIAK-3397]

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [basho/erlang_protobuffs#105]
is there any plan to support protobuf3?

**Comment by alexmoore** [comment]
Hi @ziyouchutuwenwu,

This project is no longer actively maintained, and there is no plan for protobuf3 support.

We've moved over to [gpb](https://github.com/tomas-abrahamsson/gpb) for Riak development, and recommend the same for others. `gpb` has `erlang_protobuffs` compatibility, protobuf3 support, and is actively maintained by @tomas-abrahamsson.

Thanks,
Alex
