### ISSUE TITLE
Add return/report/warnings_as_errors compile options

### ISSUE THREAD

**Issue by tuncer** [basho/erlang_protobuffs#16]
It would be highly useful to add the same return/return_warnings/return_errors/report/report_warnings/report_errors/warnings_as_errors options as available in [compile:file](http://www.erlang.org/doc/man/compile.html#file-2) and [leex:file](http://www.erlang.org/doc/man/leex.html#file-1) for erlang_protobuffs' own errors/warnings.

**Comment by lukebakken** [comment]
A PR with this feature and tests would be appreciated. If one is submitted, please reference this issue and re-open it. Thank you.
