### ISSUE TITLE
Function has_extension() doesn't understand field name

### ISSUE THREAD

**Issue by skakirill** [basho/erlang_protobuffs#31]
Hello! I don't know if there is a bug or feature.
I got files extend.proto and extensions.proto from the test/erlang_protobuffs_SUITE_data/ directory.
Then I scaned file:

``` erlang
protobuffs_compile:scan_file("extend.proto").
```

Then I ran test:

``` erlang
extension_test() ->
    Message0 = #extendable{},
    {ok, Message1} = extend_pb:set_extension(Message0, bar, 25),

    ?assertEqual(1, extend_pb:extension_size(Message1)),
    ?assertEqual({ok, 25}, extend_pb:get_extension(Message1, bar)),
    ?assert(extend_pb:has_extension(Message1, bar)),    %% <<< Why does it return false?!
    ok.
```

Test fails in last assert.
I checked extend_pb.erl. It contains:

``` erlang
    ...
    has_extension(#extendable{'$extensions' = Extensions},
              bar) ->
        dict:is_key(bar, Extensions);
    ...
    set_extension(#extendable{'$extensions' = Extensions} =
              Record,
              bar, Value) ->
        NewExtends = dict:store(126,
                    {optional, Value, sint32, none}, Extensions),
    {ok, Record#extendable{'$extensions' = NewExtends}};
    ...
```

In function has_extension() it tries to search for _atom key_ in the dictionary. 
But set_extension() inserts only _numeric key_ in dictionary.
It seems to me it's bug in the code generator.

**Comment by lukebakken** [comment]
FYI, this project (`erlang_protobuffs`) is no longer actively maintained. Please use [`gpb`](https://github.com/tomas-abrahamsson/gpb) instead. `gpb` has `erlang_protobuffs` compatibility and is actively maintained by @tomas-abrahamsson
