### ISSUE TITLE
Absence of License file

### ISSUE THREAD

**Issue by fcristovao** [basho/erlang_protobuffs#35]
Hey,

  I was wondering if this project could add a license file, so that everyone could know where it stands in using it.

  One suggestion would be the Apache License 2.0, but there are others you might feel as appropriate.

**Comment by lukebakken** [comment]
Thank you for the clarification @freke 

I have updated the [`README.md`](https://github.com/basho/erlang_protobuffs/blob/develop/README.md#authors--contributors) file as well.
