### ISSUE TITLE
Add erlang types to compiled record definitions

### ISSUE THREAD

**Issue by sebastian** [basho/erlang_protobuffs#60]
Dear Bashoers,
We have noticed that there is a lot of dialyzer related work going on in your codebase  at the moment. Cool.
To aid dialyzer we would very much like the type information that is present in .proto message definitions to transition over to the erlang world as erlang types. 
I imagine the easiest place to start would be to make the types available in the protocol buffer record definitions.

Is this on your radar? We would rather avoid duplicating your work if this is something you are already working on. If it is not something you are working on, is this something you would like a pull request on?

Thanks!

**Comment by csyangchen** [comment]
+1

**Comment by hmmr** [comment]
Currently the dilayzer warnings coming from .erl files generated by protoc are isolated and ignored (in the sense that they don't cause `make dialyzer` to fail). This is done by listing them in https://github.com/basho/riak_pb/blob/develop/dialyzer.ignore-warnings, in conjunction with some sed work in `tools.mk`.

In absence of this trick -- and supposing for a moment that all of riak code is dialyzer clean without exception or a need thereof -- the problem of missing specs and exported types in the protoc-generated files would indeed be more visible. As things stand, however, it seems to be just adequate enough a solution for now.

**Comment by lukebakken** [comment]
Hello @sebastian -

> If it is not something you are working on, is this something you would like a pull request on?

This project is basically in maintenance mode. I am going through issues and PRs and merging those that have low impact to the code, while closing issues that are stale.

We will gladly accept a PR with tests for this feature, but do not plan on implementing it at this time. If a PR is provided, please reference this issue and re-open it. Thanks!
