### ISSUE TITLE
Generate default values in hrl headers for required field(s)

### ISSUE THREAD

**Issue by madrat-** [basho/erlang_protobuffs#61]
Dear Bashoers, the proto's optional fields generates valid hrl record's fields with default values, but the required - not.

example

message Constants
{
    optional string name0 = 1 [ default = "theName" ];
    required string name1 = 2 [ default = "theName" ];
}
generates the follows code

-record(constants, {
    name0 = "theName",
    name1 = erlang:error({required, name1})
}).

**Comment by lukebakken** [comment]
@madrat - please open a pull request with test cases for your change if you would like to see it accepted. Re-open this issue and reference it when you open the PR. Thank you.
