### ISSUE TITLE
import conflict

### ISSUE THREAD

**Issue by ghost** [basho/erlang_protobuffs#71]
There is import conflict when the same proto is imported more than once in the import chain.

https://github.com/genesislive/erlang_protobuffs/commit/d51fe5d8ee5f4f99f09991dabd6b353acae917c4

**Comment by lukebakken** [comment]
FYI, this project (`erlang_protobuffs`) is no longer actively maintained. Please use [`gpb`](https://github.com/tomas-abrahamsson/gpb) instead. `gpb` has `erlang_protobuffs` compatibility and is actively maintained by @tomas-abrahamsson
