### ISSUE TITLE
Decode as list rather than binary string?

### ISSUE THREAD

**Issue by liuzhen** [basho/erlang_protobuffs#72]
When I was using utf8 with protobuffs, I noticed that protobuffs decodes string typed fields to lists, but the readme of erlang_protobuffs says "binary string" as:

```
1> protobuffs_compile:scan_file("simple.proto").
ok
2> simple_pb:decode_person(<<10,4,78,105,99,107,18,13,77,111,...>>).
{person,<<"Nick">>,<<"Mountain View">>, <<"+1 (000) 555-1234">>,25,undefined}
```

Why is that? How can I decode as binary string?

**Comment by lukebakken** [comment]
Hello -

A PR with the suggested change as well as tests for the change would be appreciated. At this time there are no additional features planned for this project. If a PR is submitted, please reference this issue and re-open it. Thank you!
