### ISSUE TITLE
a bug for imports_dir options

### ISSUE THREAD

**Issue by sysuzhang** [basho/erlang_protobuffs#73]
in file protobuffs_compile.erl, function scan_string/3 at line 68 around, there is a bug for ImportPaths variate:
ImportPaths = ["./", "src/" | proplists:get_value(imports_dir, Options, [])],
because erlang language will treat string as a list, so list operation will flatten list, for example, the code following: 

Options = [{imports_dir, "dir/"}],
ImportPaths = ["./", "src/" | proplists:get_value(imports_dir, Options, [])] 

the ImportPaths is ["./","src/",100,105,114,47], while we expect the result is ["./","src/", "dir/"]

so, I think the right code maybe :

ImportPaths = 
    case proplists:get_value(imports_dir, Options) of
	    undefined -> ["./", "src/"];
		ImportDir -> [ImportDir, "./", "src/"]
	end,
	
is there anything i am wrong?

**Comment by csyangchen** [comment]
imports_dir is supposed to be a list of dir.
