### ISSUE TITLE
basho erlang_protobuffs not working 

### ISSUE THREAD

**Issue by edukondalugorla** [basho/erlang_protobuffs#79]
below function is not working  please give solution to me
protobuffs_compile:scan_file("simple.proto").           
** exception exit: scanning_error
     in function  protobuffs_compile:parse_file/2 (protobuffs_compile.erl, line 193)
     in call from protobuffs_compile:parse_file/1 (protobuffs_compile.erl, line 183)
     in call from protobuffs_compile:scan_file/2 (protobuffs_compile.erl, line 59)

**Comment by mrallen1** [comment]
I can't reproduce this on my system, assuming that your `simple.proto` is [this test file](https://github.com/basho/erlang_protobuffs/blob/develop/test/erlang_protobuffs_SUITE_data/proto/simple.proto).  Can you provide more details?  What Erlang release are you using? What version of rebar?

**Comment by edukondalugorla** [comment]
Sorry ,I was  complied  protobuffs_compile.erl  without debug_info. thats why i got problem, So now i compiled with debug_info now  working fine.
