### ISSUE TITLE
** exception error: undefined function protobuffs:encode/3

### ISSUE THREAD

**Issue by HelloKevinTian** [basho/erlang_protobuffs#83]
I got error when I firstly used erlang_protobuffs with my rebar project.

a part of  rebar.config:
%%-------------------------------------------------
{deps_dir, "deps"}.
{deps, [
    {protobuffs, ".*", {git, "https://github.com/basho/erlang_protobuffs.git"}}
   ]}.

{proto_opts, [
              {compiler, protobuffs},
              {src_dirs, ["proto"]}
             ]}.
%%-------------------------------------------------

> rebar get-deps

> rebar compile generate

> rel/server/bin/server console

(server@127.0.0.1)1> protobuffs:encode(1, 1, uint32).
** exception error: undefined function protobuffs:encode/3

**Comment by lukebakken** [comment]
Please provide a complete project to reproduce this, and re-open this issue at that time. Thank you.
