### ISSUE TITLE
decode into binary [JIRA: RIAK-2442]

### ISSUE THREAD

**Issue by nestor5** [basho/erlang_protobuffs#98]
Is it possible to use binary instead of list in decode result?

i.e. decode into {person, <<"John Doe">>} instead of {person, "John Doe"}

The example in the documentation shows decode result of binary, but actually it decodes into lists.

**Comment by lukebakken** [comment]
FYI, this project (`erlang_protobuffs`) is no longer actively maintained. Please use [`gpb`](https://github.com/tomas-abrahamsson/gpb) instead. `gpb` has `erlang_protobuffs` compatibility and is actively maintained by @tomas-abrahamsson
